### PR TITLE
#8: Support version subdirectory structure

### LINKED ISSUE #8: Add/Use version sub directory
Hi,

I tried your OTA solution and it works as advertised, thank you for this.

I would like to add this as an enhancement for easier use of your project.

I had to create a bash script to get the files uploaded with the correct names. 
Which is fine, but if you add a version dir I think you can make your project easier to use.

```
server-root/
|- <project_name>/
|  |- version <- version file
|  |  <version dir> |- <filename1>
|  |  <version dir> |- <filename2>
|  |  <version dir> |- ...
```
This way you can use filenames without versions and keep uploading/syncing with your webserver easy.

For now this is my bash script:

```
#!/usr/bin/env bash

echo "uploading version: ${1} for ${2}"

`echo "$1" > version`

scp version mm:/var/www/html/$2/version
scp boot.py mm:/var/www/html/$2/$1_boot.py
scp main.py mm:/var/www/html/$2/$1_main.py
scp config_$2.py mm:/var/www/html/$2/$1_config.py
```

usage: `./upload.sh 1.0.4 tuinhuis_monitor`

### PR DESCRIPTION
**Pull request by olivergregorius**
Closes #8

### CODE REVIEW

**Comment by Pax-nl** [comment]
Hi @olivergregorius ,

I tested your code and got the following error:
`Something went wrong: unexpected keyword argument 'timeout'` 

It seems the urequest module does not support timeout, at least not the one bundled with micropython I use: 
`MicroPython v1.19.1 on 2022-06-18; ESP module with ESP8266`

```
>>> urequests.get('http://192.168.178.12/tuinhuis_deur/version')
<Response object at 3fff0ec0>
>>> urequests.get('http://192.168.178.12/tuinhuis_deur/version', timeout=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "urequests.py", line 116, in get
TypeError: unexpected keyword argument 'timeout'
```

This error threw me of a bit as it seems this `timeout=5` is also in the code of the main branch, but not in the `micropython_ota-1.1.0.zip` I was using. After I found this out, I removed the timeout and all seem to work both `use_version_prefix=False` and `use_version_prefix=True` options

**Comment by olivergregorius** [comment]
@Pax-IT Sigh, your Micropython build is from 2022-06-18, the timeout parameter was introduced in urequest on 2022-06-29 (https://github.com/micropython/micropython-lib/commit/a3d6d29b1b9de2bb147e0751c08a39608ebe06c8).
Your build seems to be the latest stable one for your board, whereas there are some recent nightly builds you could use.
I'm working with Raspberry Pi Pico W's - only nightly builds available, yet.

Hm, I think I will work on a solution to circumvent this issue, to stay backwards compatible! But for now at least you've found a solution yourself.

I will take over and get back to you soon!

**Comment by Pax-nl** [comment]
compiled my own firmware and I can confirm it works.
`MicroPython v1.19.1-616-g5987130af on 2022-11-07; ESP module with ESP8266`

edit: error I got with nightly build (reason I build my own)
downloaded from: https://micropython.org/download/esp8266/
```
MPY: soft reboot
Traceback (most recent call last):
  File "boot.py", line 6, in <module>
  File "micropython_ota.py", line 15
SyntaxError: invalid syntax
MicroPython v1.19.1-616-g5987130af on 2022-11-07; ESP module (1M) with ESP8266
Type "help()" for more information.
```
File "boot.py", line 6, in <module>
```
import micropython_ota
```
File "micropython_ota.py", line 15
```
            print(f'Remote version file {host}/{project}/version not found')
```

**Comment by olivergregorius** [comment]
@Pax-IT Well, good that it is now working for you. Did you encounter any more issues? Otherwise I would merge this.

**Comment by Pax-nl** [comment]
Hi @olivergregorius, 

No further issues, please merge your changes..

I have another feature request, I will create an `issues` for it..

**Pull request merged**
